name : sworddash
main : com.sworddash.sworddash.Main
version : 1.0
author : captain0potlid
api-version: 1.12
commands :
  sworddash:
    description : gives player dash sword
    usage : /sworddash